In [8]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

data = np.array([[3,5],[7,4],[2,4]])
print(data)

#Way : 1
#mean = average
mean_val = data.mean(axis=0)
print(mean_val)

#Standard Deviation
std = data.std(axis=0)
print(std)

#Mean Removal : it means mean=0, std=1
final_val = data-mean_val
print(final_val)
# print(final_val.mean(axis = 0))
# print(final_val.std(axis = 0))

#Way:2
#scale()
final = preprocessing.scale(data)
print(final)
print(final.mean(axis = 0))
print(final.std(axis = 0))


[[3 5]
 [7 4]
 [2 4]]
[4.         4.33333333]
[2.1602469  0.47140452]
[[-1.          0.66666667]
 [ 3.         -0.33333333]
 [-2.         -0.33333333]]
[[-0.46291005  1.41421356]
 [ 1.38873015 -0.70710678]
 [-0.9258201  -0.70710678]]
[0.00000000e+00 5.92118946e-16]
[1. 1.]


In [9]:
df=pd.read_csv("csvdata.csv")
print(df)
data = df[['person','male','female']]
print("===========================")
print(data)

print(data.mean(axis=0))
print("===========================")
print(data.std(axis=0))

mean_removed_data = preprocessing.scale(data)
print(mean_removed_data.mean(axis=0))
print(mean_removed_data.std(axis=0))

    year  person   male  female
0   2011   85.60  36.29   53.66
1   2010   50.47  82.88   49.72
2   2012    2.51  67.35   43.58
3   1999   50.90  84.91    6.96
4   1993    6.54  10.47   97.47
5   1997   64.46  82.18    3.43
6   2007    4.44  43.73   96.34
7   2008   94.53  10.72   53.40
8   2001    6.49  59.19   27.44
9   2004   60.61  45.69   67.21
10  1995   53.75  19.24   43.91
11  2012   97.58   1.69   10.12
12  2012   71.15  32.69   69.02
13  1991    2.57  75.02   18.07
14  2010   95.56  86.84   54.92
15  2011    4.94  14.57   15.68
16  1986   63.96  36.57   95.50
17  1983   34.10  82.32   87.78
18  2000   27.14  12.89   21.98
19  1993    9.55  20.09   21.24
20  1986   38.82  95.61   36.45
21  2010   80.38  60.01   15.21
22  2010    6.23  29.72   37.88
23  2012   28.57  13.16   16.33
24  1994   50.41  89.26   41.22
25  2010   51.71  18.92   64.39
26  1991   10.66  57.04   53.13
27  1996   91.25  10.92   54.72
28  2009   91.61  48.14   25.08
29  1995   67.79   6.81   60.41
    pers

# Sclling

In [19]:
data = np.array([[3,5],[7,4],[2,4]])

#Define A scaller for scalling the data
scaller_model= preprocessing.MinMaxScaler()


#Apply data to the model : fit
op1 = scaller_model.fit(data)


#let the model tramsfer the data according to requirnment : transform
op2=op1.transform(data)
print(op2)


[[0.2 1. ]
 [1.  0. ]
 [0.  0. ]]


In [21]:
data = np.array([[3,5],[7,4],[2,4]])

#Define A scaller for scalling the data
scaller_model= preprocessing.MinMaxScaler()

#Apply the data to model and let the model transfer the data accordingly
op = scaller_model.fit_transform(data)
print(op)

[[0.2 1. ]
 [1.  0. ]
 [0.  0. ]]


In [22]:
df=pd.read_csv("csvdata.csv")

#Define A scaller for scalling the data
scaller_model= preprocessing.MinMaxScaler()

#Apply the data to model and let the model transfer the data accordingly
op = scaller_model.fit_transform(df)
print(op)

[[9.65517241e-01 8.73987588e-01 3.68398637e-01 5.34134411e-01]
 [9.31034483e-01 5.04470390e-01 8.64459114e-01 4.92237346e-01]
 [1.00000000e+00 0.00000000e+00 6.99105622e-01 4.26945980e-01]
 [5.51724138e-01 5.08993373e-01 8.86073254e-01 3.75372182e-02]
 [3.44827586e-01 4.23898180e-02 9.34838160e-02 1.00000000e+00]
 [4.82758621e-01 6.51625118e-01 8.57005963e-01 0.00000000e+00]
 [8.27586207e-01 2.03008310e-02 4.47614991e-01 9.87983837e-01]
 [8.62068966e-01 9.67918376e-01 9.61456559e-02 5.31369630e-01]
 [6.20689655e-01 4.18638898e-02 6.12223169e-01 2.55316886e-01]
 [7.24137931e-01 6.11128642e-01 4.68483816e-01 6.78222033e-01]
 [4.13793103e-01 5.38971284e-01 1.86861158e-01 4.30455125e-01]
 [1.00000000e+00 1.00000000e+00 0.00000000e+00 7.11399405e-02]
 [1.00000000e+00 7.21994320e-01 3.30068143e-01 6.97469162e-01]
 [2.75862069e-01 6.31113916e-04 7.80770869e-01 1.55678435e-01]
 [9.31034483e-01 9.78752498e-01 9.06622658e-01 5.47532965e-01]
 [9.65517241e-01 2.55601136e-02 1.37137990e-01 1.302637